/**
 * Agentic Creator OS - Quality Evaluation MCP Server
 *
 * Heuristic (rule-based, offline) evaluation of content generated by Agentic Creator OS
 * workflows: quality scoring, hook scoring, comparisons, suggestions, and an audit trail.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { evaluateContent } from './evaluation/evaluator.js';
import { evaluateHook } from './evaluation/hook-evaluator.js';
import { trackPerformance, getMetrics } from './evaluation/metrics.js';
import { logEvaluation, getAuditTrail } from './logging/audit.js';

const server = new McpServer({ name: 'evaluator', version: '1.1.0' });

const CONTENT_TYPES = ['twitter', 'linkedin', 'instagram', 'tiktok', 'farcaster', 'blog', 'email', 'video'] as const;
const HOOK_PLATFORMS = ['twitter', 'linkedin', 'instagram', 'tiktok', 'farcaster'] as const;
const SOURCES = ['claude-code', 'opencode', 'gemini', 'custom'] as const;
const COMPARE_METRICS = ['quality', 'readability', 'engagement', 'seo', 'brand-voice'] as const;
const FOCUS_AREAS = ['hook', 'body', 'cta', 'readability', 'engagement', 'seo', 'brand-voice', 'all'] as const;

const shortText = () => z.string().max(200);
const contentText = () => z.string().min(1).max(100_000);
const context = z.object({
  workflowId: shortText().optional().describe('Workflow that produced the content'),
  sessionId: shortText().optional().describe('Agent session ID, for filtering the audit trail'),
  projectId: shortText().optional().describe('Project ID, for filtering the audit trail'),
  source: z.enum(SOURCES).default('claude-code').describe('Which assistant produced the content'),
}).describe('Where the content came from; recorded in the audit trail');

const suggestion = z.object({
  area: z.string().optional(),
  type: z.string().optional(),
  issue: z.string(),
  suggestion: z.string(),
  impact: z.string(),
}).passthrough();

const prediction = z.object({
  confidence: z.number(),
  factors: z.array(z.string()),
}).passthrough();

function ok<T extends Record<string, unknown>>(data: T) {
  const plain = JSON.parse(JSON.stringify(data)) as T;
  return { content: [{ type: 'text' as const, text: JSON.stringify(plain, null, 2) }], structuredContent: plain };
}

function fail(message: string) {
  return { content: [{ type: 'text' as const, text: message }], isError: true };
}

server.registerTool(
  'evaluator_evaluate_content',
  {
    title: 'Evaluate content quality',
    description: 'Score a draft (post, blog, email, script) 0-100 on readability, engagement potential, brand voice, platform fit, SEO and authenticity, using offline heuristics, not an LLM. Appends an audit-trail entry. Returns scores, a letter grade, an engagement prediction, suggestions and an evaluationId.',
    inputSchema: {
      content: contentText().describe('The content to evaluate'),
      contentType: z.enum(CONTENT_TYPES).describe('Format of the content, which sets the platform rules applied'),
      platform: shortText().optional().describe('Target platform, when it differs from contentType'),
      brandVoice: z.object({
        tone: z.enum(['professional', 'casual', 'authoritative', 'friendly', 'provocative']).describe('Intended tone'),
        personality: z.array(z.string().max(100)).max(20).describe('Personality traits, e.g. curious, direct'),
        keywords: z.array(z.string().max(100)).max(50).optional().describe('Words the brand wants to use'),
        avoidKeywords: z.array(z.string().max(100)).max(50).optional().describe('Words the brand avoids'),
      }).optional().describe('Brand voice to check against; omit to skip the brand-voice score'),
      context: context.optional(),
      options: z.object({
        includeSuggestions: z.boolean().default(true).describe('Include improvement suggestions'),
        strictMode: z.boolean().default(false).describe('Grade more harshly'),
        benchmarkAgainst: z.enum(['industry-average', 'top-performers', 'previous-outputs']).default('industry-average').describe('Baseline for the grade'),
      }).optional().describe('Scoring options'),
    },
    outputSchema: {
      evaluationId: z.string().describe('ID for evaluator_track_performance once the content is published'),
      scores: z.object({
        overall: z.number(),
        readability: z.number(),
        engagement: z.number(),
        brandVoice: z.number(),
        platformOptimization: z.number(),
        seo: z.number(),
        authenticity: z.number(),
      }).passthrough().describe('Scores from 0 to 100'),
      grade: z.string().describe('Letter grade'),
      engagementPrediction: prediction.describe('Predicted engagement band with confidence and factors'),
      suggestions: z.array(suggestion).describe('Improvement suggestions'),
      metadata: z.object({}).passthrough().describe('Length, word count, platform and timestamp'),
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  },
  async (input) => {
    try {
      const result = await evaluateContent(input);
      const evaluationId = await logEvaluation({
        type: 'content-evaluation',
        source: input.context?.source || 'claude-code',
        sessionId: input.context?.sessionId,
        projectId: input.context?.projectId,
        workflowId: input.context?.workflowId,
        contentType: input.contentType,
        result,
      });
      return ok({ evaluationId, ...result });
    } catch (error) {
      return fail(`Evaluation failed: ${error}`);
    }
  },
);

server.registerTool(
  'evaluator_evaluate_hook',
  {
    title: 'Evaluate hook',
    description: 'Score the opening line of a social post 0-100 on curiosity gap, specificity, emotional trigger, platform fit and known hook patterns, using offline heuristics. Appends an audit-trail entry. Returns scores, detected category, an engagement prediction and suggestions.',
    inputSchema: {
      hook: z.string().min(1).max(1000).describe('The hook or first line to score'),
      platform: z.enum(HOOK_PLATFORMS).describe('Platform the hook is written for'),
      category: z.enum(['question', 'statement', 'contradiction', 'promise', 'story', 'controversy']).optional().describe('Intended hook style; detected automatically when omitted'),
      context: context.optional(),
    },
    outputSchema: {
      evaluationId: z.string().describe('Audit-trail entry ID'),
      scores: z.object({
        overall: z.number(),
        curiosityGap: z.number(),
        specificity: z.number(),
        emotionalTrigger: z.number(),
        platformFit: z.number(),
        patternMatch: z.number(),
      }).passthrough().describe('Scores from 0 to 100'),
      category: z.string().describe('Detected or given hook category'),
      engagementPrediction: prediction.describe('Predicted engagement band with confidence and factors'),
      suggestions: z.array(suggestion).describe('Improvement suggestions'),
      metadata: z.object({}).passthrough().describe('Length, word count, platform, detected patterns and timestamp'),
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  },
  async (input) => {
    try {
      const result = evaluateHook(input);
      const evaluationId = await logEvaluation({
        type: 'hook-evaluation',
        source: input.context?.source || 'claude-code',
        sessionId: input.context?.sessionId,
        projectId: input.context?.projectId,
        workflowId: input.context?.workflowId,
        platform: input.platform,
        result,
      });
      return ok({ evaluationId, ...result });
    } catch (error) {
      return fail(`Hook evaluation failed: ${error}`);
    }
  },
);

const metricCount = () => z.number().int().min(0).max(1e12);

server.registerTool(
  'evaluator_track_performance',
  {
    title: 'Track published performance',
    description: 'Record the real engagement numbers of a published piece against an earlier evaluationId, so predicted and actual performance can be compared. Held in memory for this server session. Returns success and an accuracy percentage; cheap, local only.',
    inputSchema: {
      evaluationId: z.string().min(1).max(100).describe('evaluationId returned by evaluator_evaluate_content'),
      actualMetrics: z.object({
        impressions: metricCount().optional().describe('Impressions'),
        engagement: metricCount().optional().describe('Total engagements'),
        shares: metricCount().optional().describe('Shares or reposts'),
        comments: metricCount().optional().describe('Comments or replies'),
        saves: metricCount().optional().describe('Saves or bookmarks'),
        clicks: metricCount().optional().describe('Link clicks'),
        conversions: metricCount().optional().describe('Conversions'),
        reach: metricCount().optional().describe('Unique accounts reached'),
        followerGrowth: z.number().int().min(-1e9).max(1e9).optional().describe('Net follower change'),
      }).describe('Observed metrics; send the ones you have'),
      publishedAt: z.string().max(40).describe('When it was published, ISO 8601'),
      platform: z.string().min(1).max(50).describe('Where it was published'),
    },
    outputSchema: {
      success: z.boolean().describe('True when the metrics were recorded'),
      accuracyPercentage: z.number().describe('How close the prediction was, 0-100'),
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  },
  async (input) => {
    try {
      return ok(await trackPerformance(input));
    } catch (error) {
      return fail(`Tracking failed: ${error}`);
    }
  },
);

server.registerTool(
  'evaluator_get_metrics',
  {
    title: 'Get evaluation metrics',
    description: 'Summarise tracked performance over a time range: evaluation count, average score and prediction accuracy, top content types, trend, and breakdowns by platform and type. Use it for a periodic content review. Returns one aggregate object; reads local files only.',
    inputSchema: {
      timeRange: z.enum(['24h', '7d', '30d', '90d', 'all']).default('30d').describe('Window to aggregate'),
      contentType: z.string().max(50).optional().describe('Only this content type'),
      platform: z.string().max(50).optional().describe('Only this platform'),
      projectId: shortText().optional().describe('Only this project'),
      metricType: z.enum(['quality', 'engagement', 'improvement', 'all']).default('all').describe('Which metric family to emphasise'),
    },
    outputSchema: {
      totalEvaluations: z.number().describe('Evaluations with tracked performance'),
      averageScore: z.number().describe('Average predicted score'),
      averageAccuracy: z.number().describe('Average prediction accuracy, 0-100'),
      topPerformingContent: z.array(z.object({ type: z.string(), avgEngagement: z.number() }).passthrough()).describe('Best content types'),
      improvementTrend: z.enum(['improving', 'declining', 'stable']).describe('Direction of scores over time'),
      metricsByPlatform: z.record(z.object({}).passthrough()).describe('Counts and averages per platform'),
      metricsByType: z.record(z.object({}).passthrough()).describe('Counts and averages per content type'),
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  async (input) => {
    try {
      return ok({ ...(await getMetrics(input)) });
    } catch (error) {
      return fail(`Metrics failed: ${error}`);
    }
  },
);

server.registerTool(
  'evaluator_get_audit_trail',
  {
    title: 'Get audit trail',
    description: 'Read past evaluation log entries, newest first, filtered by session, project, source assistant (claude-code, opencode, gemini) or date range (default: last 7 days). Use it to review what was evaluated. Returns up to limit entries (default 100, max 1000).',
    inputSchema: {
      sessionId: shortText().optional().describe('Only entries from this session'),
      projectId: shortText().optional().describe('Only entries from this project'),
      source: z.enum(['claude-code', 'opencode', 'gemini', 'all']).optional().describe('Only entries from this assistant'),
      startDate: z.string().max(40).optional().describe('Earliest date, ISO 8601; default 7 days ago'),
      endDate: z.string().max(40).optional().describe('Latest date, ISO 8601; default now'),
      limit: z.number().int().min(1).max(1000).default(100).describe('Maximum entries to return'),
    },
    outputSchema: {
      entries: z.array(z.object({
        id: z.string(),
        type: z.string(),
        source: z.string(),
        timestamp: z.string(),
      }).passthrough()).describe('Audit entries, newest first, each with its full evaluation result'),
      count: z.number().describe('Entries returned'),
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  async (input) => {
    try {
      const entries = await getAuditTrail(input);
      return ok({ entries, count: entries.length });
    } catch (error) {
      return fail(`Audit trail failed: ${error}`);
    }
  },
);

server.registerTool(
  'evaluator_compare_content',
  {
    title: 'Compare content versions',
    description: 'Score an original and a revised draft with the same offline heuristics and compare them metric by metric, to confirm an edit is an improvement. Nothing is logged. Returns per-metric scores, the change and winner, and an overall verdict.',
    inputSchema: {
      contentA: contentText().describe('Original version'),
      contentB: contentText().describe('Revised version'),
      contentType: z.enum(CONTENT_TYPES).describe('Format of both versions'),
      metrics: z.array(z.enum(COMPARE_METRICS)).min(1).max(COMPARE_METRICS.length).describe('Metrics to compare'),
    },
    outputSchema: {
      comparison: z.record(z.object({
        original: z.number().nullable(),
        revised: z.number().nullable(),
        improvement: z.number().nullable(),
        percentageChange: z.string(),
        winner: z.enum(['original', 'revised', 'tie']),
      })).describe('Per-metric comparison'),
      summary: z.enum(['original', 'revised']).describe('Version that won more metrics'),
      timestamp: z.string().describe('When the comparison ran'),
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  async (input) => {
    try {
      return ok(await compareContent(input));
    } catch (error) {
      return fail(`Comparison failed: ${error}`);
    }
  },
);

server.registerTool(
  'evaluator_generate_improvements',
  {
    title: 'Generate improvements',
    description: 'Evaluate a draft with the offline blog heuristics and return the top improvement suggestions, optionally only for one area (hook, body, CTA, readability, engagement, SEO, brand voice). Nothing is logged. Returns up to numberOfSuggestions suggestions ranked by impact.',
    inputSchema: {
      content: contentText().describe('Draft to improve'),
      focusArea: z.enum(FOCUS_AREAS).default('all').describe('Only suggestions for this area'),
      numberOfSuggestions: z.number().int().min(1).max(10).default(5).describe('Maximum suggestions to return'),
    },
    outputSchema: {
      suggestions: z.array(suggestion).describe('Suggestions, most impactful first'),
      priorityOrder: z.array(z.object({ area: z.string().optional(), impact: z.string() }).passthrough()).describe('Areas in priority order'),
      timestamp: z.string().describe('When the suggestions were generated'),
    },
    annotations: { readOnlyHint: true, openWorldHint: false },
  },
  async (input) => {
    try {
      return ok(await generateImprovements(input));
    } catch (error) {
      return fail(`Improvement generation failed: ${error}`);
    }
  },
);

async function compareContent(args: { contentA: string; contentB: string; contentType: string; metrics: Array<typeof COMPARE_METRICS[number]> }) {
  const evalA = await evaluateContent({ content: args.contentA, contentType: args.contentType, options: { includeSuggestions: false } });
  const evalB = await evaluateContent({ content: args.contentB, contentType: args.contentType, options: { includeSuggestions: false } });

  const scoreKey: Record<typeof COMPARE_METRICS[number], keyof typeof evalA.scores> = {
    quality: 'overall',
    readability: 'readability',
    engagement: 'engagement',
    seo: 'seo',
    'brand-voice': 'brandVoice',
  };

  const comparison: Record<string, { original: number; revised: number; improvement: number; percentageChange: string; winner: 'original' | 'revised' | 'tie' }> = {};
  for (const metric of args.metrics) {
    const valueA = evalA.scores[scoreKey[metric]];
    const valueB = evalB.scores[scoreKey[metric]];
    const improvement = valueB - valueA;
    comparison[metric] = {
      original: valueA,
      revised: valueB,
      improvement,
      percentageChange: valueA > 0 ? ((improvement / valueA) * 100).toFixed(1) + '%' : 'N/A',
      winner: improvement > 0 ? 'revised' : improvement < 0 ? 'original' : 'tie',
    };
  }

  const wins = Object.values(comparison);
  return {
    comparison,
    summary: (wins.filter((c) => c.winner === 'revised').length > wins.filter((c) => c.winner === 'original').length ? 'revised' : 'original') as 'original' | 'revised',
    timestamp: new Date().toISOString(),
  };
}

async function generateImprovements(args: { content: string; focusArea: typeof FOCUS_AREAS[number]; numberOfSuggestions: number }) {
  const evaluation = await evaluateContent({ content: args.content, contentType: 'blog', options: { includeSuggestions: true } });

  let suggestions = evaluation.suggestions || [];
  if (args.focusArea !== 'all') {
    suggestions = suggestions.filter((s) => s.area === args.focusArea);
  }

  return {
    suggestions: suggestions.slice(0, args.numberOfSuggestions),
    priorityOrder: suggestions.map((s) => ({ area: s.area, impact: s.impact })),
    timestamp: new Date().toISOString(),
  };
}

const transport = new StdioServerTransport();
server.connect(transport).catch(console.error);

// stdout carries JSON-RPC, so the banner goes to stderr.
console.error('Agentic Creator OS Evaluator MCP Server running...');
