#!/bin/bash

# Agentic Creator OS - Config Generator
# Generates CLI-specific configs from your instance

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║          Agentic Creator OS - Config Generator           ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}! $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

usage() {
    echo "Usage: $0 <instance-name> <adapter> [output-dir]"
    echo ""
    echo "Arguments:"
    echo "  instance-name   Name of your instance (folder in instances/)"
    echo "  adapter         Target adapter: claude-code, opencode, cursor, all"
    echo "  output-dir      Optional output directory (default: outputs/)"
    echo ""
    echo "Examples:"
    echo "  $0 frankx claude-code"
    echo "  $0 my-brand all ./my-project"
    echo ""
    echo "Available instances:"
    ls -1 "$ROOT_DIR/instances" 2>/dev/null || echo "  (none found)"
}

validate_instance() {
    local instance="$1"
    local instance_dir="$ROOT_DIR/instances/$instance"

    if [ ! -d "$instance_dir" ]; then
        print_error "Instance '$instance' not found at $instance_dir"
        exit 1
    fi

    if [ ! -f "$instance_dir/brand-voice.md" ]; then
        print_warning "brand-voice.md not found - using defaults"
    fi
}

generate_claude_code() {
    local instance="$1"
    local output_dir="$2"
    local instance_dir="$ROOT_DIR/instances/$instance"

    echo "Generating Claude Code config..."

    mkdir -p "$output_dir/claude-code"

    # For now, concatenate the key files
    # In production, this would use proper templating
    {
        echo "# $instance Claude Code Configuration"
        echo ""
        echo "*Generated by Agentic Creator OS*"
        echo ""

        if [ -f "$instance_dir/brand-voice.md" ]; then
            echo "## Brand Voice"
            echo ""
            cat "$instance_dir/brand-voice.md"
            echo ""
        fi

        echo "## Agent Team"
        echo ""

        if [ -d "$instance_dir/agents" ]; then
            for agent_file in "$instance_dir/agents"/*.md; do
                if [ -f "$agent_file" ]; then
                    cat "$agent_file"
                    echo ""
                    echo "---"
                    echo ""
                fi
            done
        fi

        echo "## Skills Reference"
        echo ""
        echo "Skills are available in the \`.claude-skills/\` directory."
        echo ""

        if [ -d "$instance_dir/skills" ]; then
            echo "Instance-specific skills:"
            for skill_file in "$instance_dir/skills"/*.md; do
                if [ -f "$skill_file" ]; then
                    skill_name=$(basename "$skill_file" .md)
                    echo "- \`skill:instance/$skill_name\`"
                fi
            done
        fi

        echo ""
        echo "---"
        echo ""
        echo "*Generated: $(date '+%Y-%m-%d %H:%M:%S')*"

    } > "$output_dir/claude-code/CLAUDE.md"

    print_success "Created $output_dir/claude-code/CLAUDE.md"
}

generate_opencode() {
    local instance="$1"
    local output_dir="$2"
    local instance_dir="$ROOT_DIR/instances/$instance"

    echo "Generating OpenCode config..."

    mkdir -p "$output_dir/opencode"

    # Create a basic JSON config
    # In production, this would parse the markdown files properly
    {
        echo "{"
        echo "  \"_comment\": \"Generated by Agentic Creator OS - $(date '+%Y-%m-%d')\","
        echo "  \"identity\": {"
        echo "    \"override\": true,"
        echo "    \"name\": \"$instance\""
        echo "  },"
        echo "  \"subagents\": {"

        local first=true
        if [ -d "$instance_dir/agents" ]; then
            for agent_file in "$instance_dir/agents"/*.md; do
                if [ -f "$agent_file" ]; then
                    agent_name=$(basename "$agent_file" .md)
                    if [ "$first" = true ]; then
                        first=false
                    else
                        echo ","
                    fi
                    echo -n "    \"$agent_name\": { \"enhance\": true }"
                fi
            done
        fi

        echo ""
        echo "  }"
        echo "}"

    } > "$output_dir/opencode/oh-my-opencode.json"

    print_success "Created $output_dir/opencode/oh-my-opencode.json"
}

generate_cursor() {
    local instance="$1"
    local output_dir="$2"
    local instance_dir="$ROOT_DIR/instances/$instance"

    echo "Generating Cursor rules..."

    mkdir -p "$output_dir/cursor"

    {
        echo "# $instance Cursor Rules"
        echo ""
        echo "Generated by Agentic Creator OS"
        echo ""
        echo "## Voice"
        echo ""
        echo "Maintain the brand voice defined in the instance configuration."
        echo ""
        echo "## Code Style"
        echo ""
        echo "Follow project conventions and patterns."
        echo ""
        echo "---"
        echo ""
        echo "*Generated: $(date '+%Y-%m-%d')*"

    } > "$output_dir/cursor/.cursorrules"

    print_success "Created $output_dir/cursor/.cursorrules"
}

# Main execution
print_header

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

INSTANCE="$1"
ADAPTER="$2"
OUTPUT_DIR="${3:-$ROOT_DIR/outputs}"

validate_instance "$INSTANCE"

echo "Instance: $INSTANCE"
echo "Adapter: $ADAPTER"
echo "Output: $OUTPUT_DIR"
echo ""

case "$ADAPTER" in
    claude-code)
        generate_claude_code "$INSTANCE" "$OUTPUT_DIR"
        ;;
    opencode)
        generate_opencode "$INSTANCE" "$OUTPUT_DIR"
        ;;
    cursor)
        generate_cursor "$INSTANCE" "$OUTPUT_DIR"
        ;;
    all)
        generate_claude_code "$INSTANCE" "$OUTPUT_DIR"
        generate_opencode "$INSTANCE" "$OUTPUT_DIR"
        generate_cursor "$INSTANCE" "$OUTPUT_DIR"
        ;;
    *)
        print_error "Unknown adapter: $ADAPTER"
        echo "Available adapters: claude-code, opencode, cursor, all"
        exit 1
        ;;
esac

echo ""
print_success "Config generation complete!"
echo ""
echo "Next steps:"
echo "  1. Review generated configs in $OUTPUT_DIR"
echo "  2. Copy to your project directory"
echo "  3. Start creating with your AI partner"
